In [1]:
import pandas as pd

df = pd.read_csv('./data/raw/combined.csv')
df

,specObjID,bestObjID,z,zErr,zWarning,class,subClass,ra,dec,plate,...,lick_tio1,lick_tio2,lick_hd_a,lick_hg_a,d4000,d4000_n,d4000_red,d4000_n_red,d4000_n_blue,logM_star
0,2413991036171872256,1237665548892635380,0.227420,0.000030,0,GALAXY,NaN,221.95563,22.218022,2144,...,0.012619,0.077739,-1.478401,-4.948873,2.121900,1.878863,4.057740e+10,1.893756e+10,1.007927e+10,11.409330
1,1129339498400868352,1237658299536965763,0.071281,0.000017,0,GALAXY,NaN,165.15866,7.208513,1003,...,0.026403,0.074655,-2.116577,-5.386789,2.061926,1.948573,9.330450e+10,4.525207e+10,2.322319e+10,10.849840
2,570901386112296960,1237648722833637574,0.038903,0.000013,0,GALAXY,NaN,162.45937,1.204627,507,...,0.048907,0.071591,-2.060741,-5.488168,1.991778,1.788798,1.387951e+11,6.486300e+10,3.626067e+10,11.032180
3,1608983584809445376,1237660635458437274,0.352862,0.000074,0,GALAXY,NaN,156.45559,43.624475,1429,...,-0.013894,-0.079395,-7.033745,-6.393111,2.224673,1.986176,1.870543e+10,8.907043e+09,4.484518e+09,-9999.000000
4,987483252132440064,1237657856068813503,0.467755,0.000200,0,GALAXY,NaN,164.98392,50.170678,877,...,0.065631,0.000000,-1.548135,-6.722161,2.161519,2.402094,1.221976e+10,5.995741e+09,2.496047e+09,-9999.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913852,1517794764903180288,1237661871339339969,0.117228,0.000030,0,GALAXY,NaN,213.89404,40.080639,1348,...,0.040021,0.066458,-0.715716,-6.096879,2.079332,1.837221,3.832584e+10,1.839885e+10,1.001450e+10,10.664800
913853,2033521526514411520,1237661948654125074,0.130395,0.000046,0,GALAXY,STARFORMING,208.57542,10.536648,1806,...,0.028697,0.067188,-0.142880,-0.867500,1.813885,1.554142,2.132249e+10,9.711921e+09,6.249055e+09,10.934530
913854,568667177880676352,1237651736284037404,0.181179,0.000039,0,GALAXY,NaN,157.66636,2.090215,505,...,0.037685,0.042095,-1.559534,-4.833918,1.809716,1.650616,2.761160e+10,1.318152e+10,7.985815e+09,11.184710
913855,441527615912699904,1237663716018815035,0.041375,0.000008,0,GALAXY,STARFORMING,10.19812,0.621876,392,...,0.009098,0.039474,3.663647,0.686859,1.415187,1.222426,9.388226e+10,4.470850e+10,3.657359e+10,9.741333
913856,1085520386705090560,1237658613054177372,0.109069,0.000015,0,GALAXY,STARFORMING,167.26338,48.777156,964,...,0.005949,0.016553,3.139528,2.696660,1.410719,1.290290,2.735082e+10,1.357548e+10,1.052126e+10,10.302820